fragment LayoutQueryFragment on Query {
  global(relativePath: "index.json") {
    ...GlobalParts
  }
}

fragment BlogPostParts on Blog {
  title
  date
  heroImage
  canonicalUrl
  _body
  author {
    ... on Author {
      name
      avatar
    }
  }
}
