query pageQuery {
  ...LayoutQueryFragment
}

# TODO: Add sorting options
query reviewPageQuery {
  ...LayoutQueryFragment
  reviewConnection(sort: "score") {
    edges {
      node {
        id
        score
        date
        restaurant {
          ... on Restaurant {
            ...RestaurantParts
          }
        }
        author {
          ... on Author {
            ...AuthorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query reviewQuery($relativePath: String!) {
  ...LayoutQueryFragment
  review(relativePath: $relativePath) {
    ...ReviewParts
    restaurant {
      ... on Restaurant {
        name
        url
      }
    }
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}

query topReviewQuery {
  ...LayoutQueryFragment
  reviewConnection(sort: "score", last: 1) {
    edges {
      node {
        ...ReviewParts
        restaurant {
          ... on Restaurant {
            name
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

# Deliberately does NOT use ...BlogPostParts: that fragment pulls _body, which
# would ship the full text of every post to render a grid of cards.
query blogListQuery {
  ...LayoutQueryFragment
  blogConnection {
    edges {
      node {
        title
        date
        heroImage
        author {
          ... on Author {
            name
            avatar
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query blogQuery($relativePath: String!) {
  ...LayoutQueryFragment
  blog(relativePath: $relativePath) {
    ...BlogPostParts
  }
}
