query pageQuery {
  ...LayoutQueryFragment
  postConnection {
    edges {
      node {
        id
        _values
        date
        author {
          ... on Author {
            ...AuthorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

# TODO: Add sorting options
query reviewPageQuery {
  ...LayoutQueryFragment
  reviewConnection(sort: "score") {
    edges {
      node {
        id
        score
        date
        restaurant {
          ... on Restaurant {
            ...RestaurantParts
          }
        }
        author {
          ... on Author {
            ...AuthorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}

query reviewQuery($relativePath: String!) {
  ...LayoutQueryFragment
  review(relativePath: $relativePath) {
    ...ReviewParts
    restaurant {
      ... on Restaurant {
        name
        url
      }
    }
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}
